baseURL: "https://skowrons.github.io/skowron-www"
title: "Maximilian Skowron"
copyright: "© Maximilian Skowron"
#defaultContentLanguage: de
#languages:
#  en:
#    languageName: English
#    weight: 2
#  de:
#    languageName: Deutsch
#    weight: 1
menu:
  main:
    - identifier: home
      name: Home
      title: home page
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      title: blog section
      url: /blog/
      weight: 110
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
